# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083bb08257fb5cd117d8e89ae8a93af68390502156e0e42f7ba833a5471df1df110727e9cbe1cd610608f5745e1b5a3930deb66a3512f4985ef514c2649a178f

test:
  secret_key_base: 38a3067a87eba72ba5e407de94646fa110770a8c8358039356a71db577aec440a03af866fd70e44c37c4e82e3d03cf17ea84abd600e10986f72871bbedef8a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
